In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("dt.csv")

In [3]:
df.describe

<bound method NDFrame.describe of                  Name  projects-done  Tech ID                  Role  \
0    Arshia Chandarki            2.0      1.0       Project Manager
1     Nazia Chandarki            2.0      2.0        UI/UX Designer
2         Ayesha Khan            2.0      3.0        UI/UX Designer
3       Ayushi Gautam            2.0      4.0  Cybersecurity Intern
4     Sakshi Chudekar            2.0      5.0       Project Manager
5      Shrawani Botre            2.0      NaN     Backend Developer
6         Ketan Butta            2.0      7.0     Backend Developer
7       Tanmay Shinde            2.0      8.0        UI/UX Designer
8       Jannat Shaikh            2.0      9.0     Backend Developer
9       Tauhid Shaikh            2.0     10.0           AI Engineer
10      Pratik Palkar            2.0     11.0  Cybersecurity Intern
11  Kruthika Janvekar            2.0     12.0           AI Engineer
12        Prerna Shah            2.0      NaN         Web Developer
13  Harshita Indurkar            2.0     14.0  Cybersecurity Intern
14   Darshan Palrecha            2.0     15.0  Cybersecurity Intern
15         Ayush Jain            2.0     16.0     Backend Developer
16    Sumaida Tamboli            NaN     17.0       Project Manager
17         Diya Pinto            2.0     18.0         Web Developer
18            Amrutha            2.0     19.0         Web Developer
19          Khalnayak            2.0     20.0         Web Developer
20            Abhinav            2.0     21.0  Cybersecurity Intern
21     Suraj pancholi            2.0     22.0        UI/UX Designer
22       Sushmita sen            2.0     23.0     Backend Developer
23        Arjun Reddy            2.0     24.0        UI/UX Designer
24             Aanand            2.0     25.0         Web Developer
25           Abhishek            2.0     26.0  Cybersecurity Intern
26          Priyanshu            2.0     27.0     Backend Developer
27      Mehtab Sanadi            2.0     28.0       Project Manager
28        Aryan Pawar            2.0     29.0  Cybersecurity Intern
29         Nihal Josh            2.0     30.0     Backend Developer

             Project Worked On
0     Smart Traffic Management
1       Cybersecurity Research
2                 Online Store
3          Technologia Website
4                          NaN
5      IoT Women Safety Device
6      IoT Women Safety Device
7          Technologia Website
8       Cybersecurity Research
9       Fraud Detection System
10  Game Recommendation System
11                         NaN
12         E-learning Platform
13         E-learning Platform
14         Technologia Website
15                         NaN
16            Hasbaird Website
17      AR Shopping Experience
18         E-learning Platform
19                Online Store
20       Health Monitoring App
21      Fraud Detection System
22                         NaN
23     IoT Women Safety Device
24    Finance Prediction Model
25                         NaN
26      AR Shopping Experience
27  Game Recommendation System
28          AI Routine Tracker
29                Online Store  >

In [4]:
df.head

<bound method NDFrame.head of                  Name  projects-done  Tech ID                  Role  \
0    Arshia Chandarki            2.0      1.0       Project Manager
1     Nazia Chandarki            2.0      2.0        UI/UX Designer
2         Ayesha Khan            2.0      3.0        UI/UX Designer
3       Ayushi Gautam            2.0      4.0  Cybersecurity Intern
4     Sakshi Chudekar            2.0      5.0       Project Manager
5      Shrawani Botre            2.0      NaN     Backend Developer
6         Ketan Butta            2.0      7.0     Backend Developer
7       Tanmay Shinde            2.0      8.0        UI/UX Designer
8       Jannat Shaikh            2.0      9.0     Backend Developer
9       Tauhid Shaikh            2.0     10.0           AI Engineer
10      Pratik Palkar            2.0     11.0  Cybersecurity Intern
11  Kruthika Janvekar            2.0     12.0           AI Engineer
12        Prerna Shah            2.0      NaN         Web Developer
13  Harshita Indurkar            2.0     14.0  Cybersecurity Intern
14   Darshan Palrecha            2.0     15.0  Cybersecurity Intern
15         Ayush Jain            2.0     16.0     Backend Developer
16    Sumaida Tamboli            NaN     17.0       Project Manager
17         Diya Pinto            2.0     18.0         Web Developer
18            Amrutha            2.0     19.0         Web Developer
19          Khalnayak            2.0     20.0         Web Developer
20            Abhinav            2.0     21.0  Cybersecurity Intern
21     Suraj pancholi            2.0     22.0        UI/UX Designer
22       Sushmita sen            2.0     23.0     Backend Developer
23        Arjun Reddy            2.0     24.0        UI/UX Designer
24             Aanand            2.0     25.0         Web Developer
25           Abhishek            2.0     26.0  Cybersecurity Intern
26          Priyanshu            2.0     27.0     Backend Developer
27      Mehtab Sanadi            2.0     28.0       Project Manager
28        Aryan Pawar            2.0     29.0  Cybersecurity Intern
29         Nihal Josh            2.0     30.0     Backend Developer

             Project Worked On
0     Smart Traffic Management
1       Cybersecurity Research
2                 Online Store
3          Technologia Website
4                          NaN
5      IoT Women Safety Device
6      IoT Women Safety Device
7          Technologia Website
8       Cybersecurity Research
9       Fraud Detection System
10  Game Recommendation System
11                         NaN
12         E-learning Platform
13         E-learning Platform
14         Technologia Website
15                         NaN
16            Hasbaird Website
17      AR Shopping Experience
18         E-learning Platform
19                Online Store
20       Health Monitoring App
21      Fraud Detection System
22                         NaN
23     IoT Women Safety Device
24    Finance Prediction Model
25                         NaN
26      AR Shopping Experience
27  Game Recommendation System
28          AI Routine Tracker
29                Online Store  >

In [5]:
df.info

<bound method DataFrame.info of                  Name  projects-done  Tech ID                  Role  \
0    Arshia Chandarki            2.0      1.0       Project Manager
1     Nazia Chandarki            2.0      2.0        UI/UX Designer
2         Ayesha Khan            2.0      3.0        UI/UX Designer
3       Ayushi Gautam            2.0      4.0  Cybersecurity Intern
4     Sakshi Chudekar            2.0      5.0       Project Manager
5      Shrawani Botre            2.0      NaN     Backend Developer
6         Ketan Butta            2.0      7.0     Backend Developer
7       Tanmay Shinde            2.0      8.0        UI/UX Designer
8       Jannat Shaikh            2.0      9.0     Backend Developer
9       Tauhid Shaikh            2.0     10.0           AI Engineer
10      Pratik Palkar            2.0     11.0  Cybersecurity Intern
11  Kruthika Janvekar            2.0     12.0           AI Engineer
12        Prerna Shah            2.0      NaN         Web Developer
13  Harshita Indurkar            2.0     14.0  Cybersecurity Intern
14   Darshan Palrecha            2.0     15.0  Cybersecurity Intern
15         Ayush Jain            2.0     16.0     Backend Developer
16    Sumaida Tamboli            NaN     17.0       Project Manager
17         Diya Pinto            2.0     18.0         Web Developer
18            Amrutha            2.0     19.0         Web Developer
19          Khalnayak            2.0     20.0         Web Developer
20            Abhinav            2.0     21.0  Cybersecurity Intern
21     Suraj pancholi            2.0     22.0        UI/UX Designer
22       Sushmita sen            2.0     23.0     Backend Developer
23        Arjun Reddy            2.0     24.0        UI/UX Designer
24             Aanand            2.0     25.0         Web Developer
25           Abhishek            2.0     26.0  Cybersecurity Intern
26          Priyanshu            2.0     27.0     Backend Developer
27      Mehtab Sanadi            2.0     28.0       Project Manager
28        Aryan Pawar            2.0     29.0  Cybersecurity Intern
29         Nihal Josh            2.0     30.0     Backend Developer

             Project Worked On
0     Smart Traffic Management
1       Cybersecurity Research
2                 Online Store
3          Technologia Website
4                          NaN
5      IoT Women Safety Device
6      IoT Women Safety Device
7          Technologia Website
8       Cybersecurity Research
9       Fraud Detection System
10  Game Recommendation System
11                         NaN
12         E-learning Platform
13         E-learning Platform
14         Technologia Website
15                         NaN
16            Hasbaird Website
17      AR Shopping Experience
18         E-learning Platform
19                Online Store
20       Health Monitoring App
21      Fraud Detection System
22                         NaN
23     IoT Women Safety Device
24    Finance Prediction Model
25                         NaN
26      AR Shopping Experience
27  Game Recommendation System
28          AI Routine Tracker
29                Online Store  >

In [6]:
df.columns

Index(['Name', 'projects-done', 'Tech ID', 'Role', 'Project Worked On'], dtype='object')

In [7]:
df.describe()

       projects-done    Tech ID
count           29.0  28.000000
mean             2.0  15.928571
std              0.0   8.914942
min              2.0   1.000000
25%              2.0   8.750000
50%              2.0  16.500000
75%              2.0  23.250000
max              2.0  30.000000

In [8]:
print(' rows present:',df.shape[0])
print(' columns present:',df.shape[1])

 rows present: 30
 columns present: 5

In [9]:
print (' the total is' ,df.info() )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               30 non-null     object
 1   projects-done      29 non-null     float64
 2   Tech ID            28 non-null     float64
 3   Role               30 non-null     object
 4   Project Worked On  25 non-null     object
dtypes: float64(2), object(3)
memory usage: 1.3+ KB
 the total is None

In [10]:
df.iloc[:8] # index loc means starts by index

,Name,projects-done,Tech ID,Role,Project Worked On
0,Arshia Chandarki,2.0,1.0,Project Manager,Smart Traffic Management
1,Nazia Chandarki,2.0,2.0,UI/UX Designer,Cybersecurity Research
2,Ayesha Khan,2.0,3.0,UI/UX Designer,Online Store
3,Ayushi Gautam,2.0,4.0,Cybersecurity Intern,Technologia Website
4,Sakshi Chudekar,2.0,5.0,Project Manager,NaN
5,Shrawani Botre,2.0,NaN,Backend Developer,IoT Women Safety Device
6,Ketan Butta,2.0,7.0,Backend Developer,IoT Women Safety Device
7,Tanmay Shinde,2.0,8.0,UI/UX Designer,Technologia Website

In [11]:
df.tail(1)

          Name  projects-done  Tech ID               Role Project Worked On
29  Nihal Josh            2.0     30.0  Backend Developer      Online Store

In [12]:
print('Total number of rows:',df.shape[0],'\nTotal number of columns:',df.shape[1])

Total number of rows: 30
Total number of columns: 5

In [13]:
df.isnull()

     Name  projects-done  Tech ID   Role  Project Worked On
0   False          False    False  False              False
1   False          False    False  False              False
2   False          False    False  False              False
3   False          False    False  False              False
4   False          False    False  False               True
5   False          False     True  False              False
6   False          False    False  False              False
7   False          False    False  False              False
8   False          False    False  False              False
9   False          False    False  False              False
10  False          False    False  False              False
11  False          False    False  False               True
12  False          False     True  False              False
13  False          False    False  False              False
14  False          False    False  False              False
15  False          False    False  False               True
16  False           True    False  False              False
17  False          False    False  False              False
18  False          False    False  False              False
19  False          False    False  False              False
20  False          False    False  False              False
21  False          False    False  False              False
22  False          False    False  False               True
23  False          False    False  False              False
24  False          False    False  False              False
25  False          False    False  False               True
26  False          False    False  False              False
27  False          False    False  False              False
28  False          False    False  False              False
29  False          False    False  False              False

In [14]:
df.isna().sum()  #yto count null

Name                 0
projects-done        1
Tech ID              2
Role                 0
Project Worked On    5
dtype: int64

In [15]:
df.bfill()

,Name,projects-done,Tech ID,Role,Project Worked On
0,Arshia Chandarki,2.0,1.0,Project Manager,Smart Traffic Management
1,Nazia Chandarki,2.0,2.0,UI/UX Designer,Cybersecurity Research
2,Ayesha Khan,2.0,3.0,UI/UX Designer,Online Store
3,Ayushi Gautam,2.0,4.0,Cybersecurity Intern,Technologia Website
4,Sakshi Chudekar,2.0,5.0,Project Manager,IoT Women Safety Device
5,Shrawani Botre,2.0,7.0,Backend Developer,IoT Women Safety Device
6,Ketan Butta,2.0,7.0,Backend Developer,IoT Women Safety Device
7,Tanmay Shinde,2.0,8.0,UI/UX Designer,Technologia Website
8,Jannat Shaikh,2.0,9.0,Backend Developer,Cybersecurity Research
9,Tauhid Shaikh,2.0,10.0,AI Engineer,Fraud Detection System
10,Pratik Palkar,2.0,11.0,Cybersecurity Intern,Game Recommendation System
11,Kruthika Janvekar,2.0,12.0,AI Engineer,E-learning Platform
12,Prerna Shah,2.0,14.0,Web Developer,E-learning Platform
13,Harshita Indurkar,2.0,14.0,Cybersecurity Intern,E-learning Platform
14,Darshan Palrecha,2.0,15.0,Cybersecurity Intern,Technologia Website
15,Ayush Jain,2.0,16.0,Backend Developer,Hasbaird Website
16,Sumaida Tamboli,2.0,17.0,Project Manager,Hasbaird Website
17,Diya Pinto,2.0,18.0,Web Developer,AR Shopping Experience
18,Amrutha,2.0,19.0,Web Developer,E-learning Platform
19,Khalnayak,2.0,20.0,Web Developer,Online Store
20,Abhinav,2.0,21.0,Cybersecurity Intern,Health Monitoring App
21,Suraj pancholi,2.0,22.0,UI/UX Designer,Fraud Detection System
22,Sushmita sen,2.0,23.0,Backend Developer,IoT Women Safety Device
23,Arjun Reddy,2.0,24.0,UI/UX Designer,IoT Women Safety Device
24,Aanand,2.0,25.0,Web Developer,Finance Prediction Model
25,Abhishek,2.0,26.0,Cybersecurity Intern,AR Shopping Experience
26,Priyanshu,2.0,27.0,Backend Developer,AR Shopping Experience
27,Mehtab Sanadi,2.0,28.0,Project Manager,Game Recommendation System
28,Aryan Pawar,2.0,29.0,Cybersecurity Intern,AI Routine Tracker
29,Nihal Josh,2.0,30.0,Backend Developer,Online Store

In [16]:
 df.ffill()

,Name,projects-done,Tech ID,Role,Project Worked On
0,Arshia Chandarki,2.0,1.0,Project Manager,Smart Traffic Management
1,Nazia Chandarki,2.0,2.0,UI/UX Designer,Cybersecurity Research
2,Ayesha Khan,2.0,3.0,UI/UX Designer,Online Store
3,Ayushi Gautam,2.0,4.0,Cybersecurity Intern,Technologia Website
4,Sakshi Chudekar,2.0,5.0,Project Manager,Technologia Website
5,Shrawani Botre,2.0,5.0,Backend Developer,IoT Women Safety Device
6,Ketan Butta,2.0,7.0,Backend Developer,IoT Women Safety Device
7,Tanmay Shinde,2.0,8.0,UI/UX Designer,Technologia Website
8,Jannat Shaikh,2.0,9.0,Backend Developer,Cybersecurity Research
9,Tauhid Shaikh,2.0,10.0,AI Engineer,Fraud Detection System
10,Pratik Palkar,2.0,11.0,Cybersecurity Intern,Game Recommendation System
11,Kruthika Janvekar,2.0,12.0,AI Engineer,Game Recommendation System
12,Prerna Shah,2.0,12.0,Web Developer,E-learning Platform
13,Harshita Indurkar,2.0,14.0,Cybersecurity Intern,E-learning Platform
14,Darshan Palrecha,2.0,15.0,Cybersecurity Intern,Technologia Website
15,Ayush Jain,2.0,16.0,Backend Developer,Technologia Website
16,Sumaida Tamboli,2.0,17.0,Project Manager,Hasbaird Website
17,Diya Pinto,2.0,18.0,Web Developer,AR Shopping Experience
18,Amrutha,2.0,19.0,Web Developer,E-learning Platform
19,Khalnayak,2.0,20.0,Web Developer,Online Store
20,Abhinav,2.0,21.0,Cybersecurity Intern,Health Monitoring App
21,Suraj pancholi,2.0,22.0,UI/UX Designer,Fraud Detection System
22,Sushmita sen,2.0,23.0,Backend Developer,Fraud Detection System
23,Arjun Reddy,2.0,24.0,UI/UX Designer,IoT Women Safety Device
24,Aanand,2.0,25.0,Web Developer,Finance Prediction Model
25,Abhishek,2.0,26.0,Cybersecurity Intern,Finance Prediction Model
26,Priyanshu,2.0,27.0,Backend Developer,AR Shopping Experience
27,Mehtab Sanadi,2.0,28.0,Project Manager,Game Recommendation System
28,Aryan Pawar,2.0,29.0,Cybersecurity Intern,AI Routine Tracker
29,Nihal Josh,2.0,30.0,Backend Developer,Online Store

In [17]:
x= df["Tech ID"].mean()

In [18]:
x

np.float64(15.928571428571429)

In [19]:
df["Tech ID"].fillna(x)

0      1.000000
1      2.000000
2      3.000000
3      4.000000
4      5.000000
5     15.928571
6      7.000000
7      8.000000
8      9.000000
9     10.000000
10    11.000000
11    12.000000
12    15.928571
13    14.000000
14    15.000000
15    16.000000
16    17.000000
17    18.000000
18    19.000000
19    20.000000
20    21.000000
21    22.000000
22    23.000000
23    24.000000
24    25.000000
25    26.000000
26    27.000000
27    28.000000
28    29.000000
29    30.000000
Name: Tech ID, dtype: float64

In [20]:
df.fillna(x)

,Name,projects-done,Tech ID,Role,Project Worked On
0,Arshia Chandarki,2.000000,1.000000,Project Manager,Smart Traffic Management
1,Nazia Chandarki,2.000000,2.000000,UI/UX Designer,Cybersecurity Research
2,Ayesha Khan,2.000000,3.000000,UI/UX Designer,Online Store
3,Ayushi Gautam,2.000000,4.000000,Cybersecurity Intern,Technologia Website
4,Sakshi Chudekar,2.000000,5.000000,Project Manager,15.928571
5,Shrawani Botre,2.000000,15.928571,Backend Developer,IoT Women Safety Device
6,Ketan Butta,2.000000,7.000000,Backend Developer,IoT Women Safety Device
7,Tanmay Shinde,2.000000,8.000000,UI/UX Designer,Technologia Website
8,Jannat Shaikh,2.000000,9.000000,Backend Developer,Cybersecurity Research
9,Tauhid Shaikh,2.000000,10.000000,AI Engineer,Fraud Detection System
10,Pratik Palkar,2.000000,11.000000,Cybersecurity Intern,Game Recommendation System
11,Kruthika Janvekar,2.000000,12.000000,AI Engineer,15.928571
12,Prerna Shah,2.000000,15.928571,Web Developer,E-learning Platform
13,Harshita Indurkar,2.000000,14.000000,Cybersecurity Intern,E-learning Platform
14,Darshan Palrecha,2.000000,15.000000,Cybersecurity Intern,Technologia Website
15,Ayush Jain,2.000000,16.000000,Backend Developer,15.928571
16,Sumaida Tamboli,15.928571,17.000000,Project Manager,Hasbaird Website
17,Diya Pinto,2.000000,18.000000,Web Developer,AR Shopping Experience
18,Amrutha,2.000000,19.000000,Web Developer,E-learning Platform
19,Khalnayak,2.000000,20.000000,Web Developer,Online Store
20,Abhinav,2.000000,21.000000,Cybersecurity Intern,Health Monitoring App
21,Suraj pancholi,2.000000,22.000000,UI/UX Designer,Fraud Detection System
22,Sushmita sen,2.000000,23.000000,Backend Developer,15.928571
23,Arjun Reddy,2.000000,24.000000,UI/UX Designer,IoT Women Safety Device
24,Aanand,2.000000,25.000000,Web Developer,Finance Prediction Model
25,Abhishek,2.000000,26.000000,Cybersecurity Intern,15.928571
26,Priyanshu,2.000000,27.000000,Backend Developer,AR Shopping Experience
27,Mehtab Sanadi,2.000000,28.000000,Project Manager,Game Recommendation System
28,Aryan Pawar,2.000000,29.000000,Cybersecurity Intern,AI Routine Tracker
29,Nihal Josh,2.000000,30.000000,Backend Developer,Online Store

In [21]:
df2 = df.copy()

In [24]:
for col in df.columns:
    if col in df2.columns and df2[col].isnull().any():
        df2[col] = df2[col].fillna(x)  # Fill NaN values with 'x'
print(df2)

                 Name  projects-done    Tech ID                  Role  \
0    Arshia Chandarki       2.000000   1.000000       Project Manager
1     Nazia Chandarki       2.000000   2.000000        UI/UX Designer
2         Ayesha Khan       2.000000   3.000000        UI/UX Designer
3       Ayushi Gautam       2.000000   4.000000  Cybersecurity Intern
4     Sakshi Chudekar       2.000000   5.000000       Project Manager
5      Shrawani Botre       2.000000  15.928571     Backend Developer
6         Ketan Butta       2.000000   7.000000     Backend Developer
7       Tanmay Shinde       2.000000   8.000000        UI/UX Designer
8       Jannat Shaikh       2.000000   9.000000     Backend Developer
9       Tauhid Shaikh       2.000000  10.000000           AI Engineer
10      Pratik Palkar       2.000000  11.000000  Cybersecurity Intern
11  Kruthika Janvekar       2.000000  12.000000           AI Engineer
12        Prerna Shah       2.000000  15.928571         Web Developer
13  Harshita Indurkar       2.000000  14.000000  Cybersecurity Intern
14   Darshan Palrecha       2.000000  15.000000  Cybersecurity Intern
15         Ayush Jain       2.000000  16.000000     Backend Developer
16    Sumaida Tamboli      15.928571  17.000000       Project Manager
17         Diya Pinto       2.000000  18.000000         Web Developer
18            Amrutha       2.000000  19.000000         Web Developer
19          Khalnayak       2.000000  20.000000         Web Developer
20            Abhinav       2.000000  21.000000  Cybersecurity Intern
21     Suraj pancholi       2.000000  22.000000        UI/UX Designer
22       Sushmita sen       2.000000  23.000000     Backend Developer
23        Arjun Reddy       2.000000  24.000000        UI/UX Designer
24             Aanand       2.000000  25.000000         Web Developer
25           Abhishek       2.000000  26.000000  Cybersecurity Intern
26          Priyanshu       2.000000  27.000000     Backend Developer
27      Mehtab Sanadi       2.000000  28.000000       Project Manager
28        Aryan Pawar       2.000000  29.000000  Cybersecurity Intern
29         Nihal Josh       2.000000  30.000000     Backend Developer

             Project Worked On
0     Smart Traffic Management
1       Cybersecurity Research
2                 Online Store
3          Technologia Website
4                    15.928571
5      IoT Women Safety Device
6      IoT Women Safety Device
7          Technologia Website
8       Cybersecurity Research
9       Fraud Detection System
10  Game Recommendation System
11                   15.928571
12         E-learning Platform
13         E-learning Platform
14         Technologia Website
15                   15.928571
16            Hasbaird Website
17      AR Shopping Experience
18         E-learning Platform
19                Online Store
20       Health Monitoring App
21      Fraud Detection System
22                   15.928571
23     IoT Women Safety Device
24    Finance Prediction Model
25                   15.928571
26      AR Shopping Experience
27  Game Recommendation System
28          AI Routine Tracker
29                Online Store